In [1]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures

# Esempio con una singola feature
print("ESEMPIO 1: Una singola feature")
X_single = np.array([[1], [2], [3]])
print("\nDati originali:")
print(X_single)

ESEMPIO 1: Una singola feature

Dati originali:
[[1]
 [2]
 [3]]


In [ ]:
# Grado 2
poly_2 = PolynomialFeatures(degree=2)
X_poly_2 = poly_2.fit_transform(X_single)
print("\nFeature polinomiali (grado 2):")
print(X_poly_2)
print("Nomi delle feature:")
print(poly_2.get_feature_names_out(['x']))


Feature polinomiali (grado 2):
[[1. 1. 1.]
 [1. 2. 4.]
 [1. 3. 9.]]
Nomi delle feature:
['1' 'x' 'x^2']


In [2]:
# Esempio con due feature
print("\nESEMPIO 2: Due feature")
X_double = np.array([[1, 2],
                    [3, 4],
                    [5, 6]])
print("\nDati originali:")
print(X_double)


ESEMPIO 2: Due feature

Dati originali:
[[1 2]
 [3 4]
 [5 6]]


In [3]:
# Grado 2 con due feature
poly_2_double = PolynomialFeatures(degree=2)
X_poly_2_double = poly_2_double.fit_transform(X_double)
print("\nFeature polinomiali (grado 2):")
print(X_poly_2_double)
print("Nomi delle feature:")
print(poly_2_double.get_feature_names_out(['x1', 'x2']))


Feature polinomiali (grado 2):
[[ 1.  1.  2.  1.  2.  4.]
 [ 1.  3.  4.  9. 12. 16.]
 [ 1.  5.  6. 25. 30. 36.]]
Nomi delle feature:
['1' 'x1' 'x2' 'x1^2' 'x1 x2' 'x2^2']


In [4]:
# Esempio con grado 3
print("\nESEMPIO 3: Una feature con grado 3")
poly_3 = PolynomialFeatures(degree=3)
X_poly_3 = poly_3.fit_transform(X_single)
print("\nFeature polinomiali (grado 3):")
print(X_poly_3)
print("Nomi delle feature:")
print(poly_3.get_feature_names_out(['x']))


ESEMPIO 3: Una feature con grado 3

Feature polinomiali (grado 3):
[[ 1.  1.  1.  1.]
 [ 1.  2.  4.  8.]
 [ 1.  3.  9. 27.]]
Nomi delle feature:
['1' 'x' 'x^2' 'x^3']


In [5]:
# Esempio senza bias (termine costante)
print("\nESEMPIO 4: Senza termine costante")
poly_no_bias = PolynomialFeatures(degree=2, include_bias=False)
X_poly_no_bias = poly_no_bias.fit_transform(X_single)
print("\nFeature polinomiali (senza bias):")
print(X_poly_no_bias)
print("Nomi delle feature:")
print(poly_no_bias.get_feature_names_out(['x']))


ESEMPIO 4: Senza termine costante

Feature polinomiali (senza bias):
[[1. 1.]
 [2. 4.]
 [3. 9.]]
Nomi delle feature:
['x' 'x^2']
